import assert from 'node:assert/strict';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
const { chromium, webkit } = await import(process.env.SPORT_GUIDE_PLAYWRIGHT_MODULE || 'playwright');
const engine = process.env.SPORT_GUIDE_ENGINE || 'webkit';
const base = process.env.SPORT_GUIDE_URL || 'http://127.0.0.1:4328/francophone-sport-careers/';
const out = process.env.SPORT_GUIDE_ARTIFACTS || '/tmp/sport-i18n-check/tests';
await mkdir(out,{recursive:true});
const source = JSON.parse(await readFile(new URL('../../public/francophone-sport-careers/data/catalog.json',import.meta.url),'utf8'));
const resources = Object.fromEntries(await Promise.all(['fr','en','zh'].map(async l=>[l,JSON.parse(await readFile(new URL(`../../public/francophone-sport-careers/locales/${l}.json`,import.meta.url),'utf8'))])));
const b = engine === 'webkit' ? await webkit.launch() : await chromium.launch({channel:'chrome'});
const ctx=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,locale:'en-US'});
const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const checks=[];
async function check(name,run){await run();checks.push(name);console.log('PASS',name);}
async function visit(locale,hash=''){await p.goto(base+(locale?'?lang='+locale:'')+hash);await p.locator('#results').waitFor();}
async function count(n){await p.waitForFunction(n=>document.querySelectorAll('#results article').length===n,n);}
async function language(l){await p.locator(`[data-language=${l}]`).click();await p.waitForFunction(l=>document.documentElement.lang===(l==='zh'?'zh-CN':l),l);await p.waitForFunction(title=>document.querySelector('h1').textContent===title,resources[l].ui.site.title);}
async function close(){await p.locator('[data-action=close]').click();await p.waitForFunction(()=>!document.querySelector('dialog').open);}
async function noOverflow(){
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'document horizontal overflow');
 if(await p.locator('dialog').isVisible()){
  assert(await p.locator('.dialog-body').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'detail horizontal overflow');
  for(const locator of [p.locator('.dialog-tools'),p.locator('.detail-footer')]){const r=await locator.boundingBox(),vp=p.viewportSize();assert(r.x>=0&&r.x+r.width<=vp.width+1&&r.y>=0&&r.y+r.height<=vp.height+1,'fixed dialog controls overflow');}
 }
}
async function noChinese(locale){
 if(locale==='zh')return;
 const text=await p.evaluate(()=>Array.from(document.querySelectorAll('main,dialog')).map(el=>el.innerText).join(' ').replaceAll('中文',''));
 assert(!/[\u3400-\u9fff]/u.test(text),'Chinese prose leaked into '+locale);
 const attrs=await p.evaluate(()=>Array.from(document.querySelectorAll('[aria-label],input[placeholder],button[title]')).map(el=>[el.getAttribute('aria-label'),el.getAttribute('placeholder'),el.getAttribute('title')].join(' ')).join(' '));
 assert(!/[\u3400-\u9fff]/u.test(attrs),'Chinese accessibility text leaked into '+locale);
}
await check('Clean browser defaults to French, regardless of browser language',async()=>{await visit();await count(5);assert.equal(await p.locator('html').getAttribute('lang'),'fr');assert.equal(await p.locator('h1').innerText(),resources.fr.ui.site.title);assert((await p.locator('meta[name=description]').getAttribute('content')).includes('Stages'));});
await check('Language selection persists across refresh and bare URLs',async()=>{await language('en');await p.reload();assert.equal(await p.locator('html').getAttribute('lang'),'en');await visit();assert.equal(await p.locator('html').getAttribute('lang'),'en');await visit('fr');assert.equal(await p.locator('html').getAttribute('lang'),'fr');await visit('unsupported');assert.equal(await p.locator('html').getAttribute('lang'),'en');});
await check('Switching retains keyword, categories, filters and matching records',async()=>{await visit('fr','#internships?tab=all&q=设计');await count(1);const before=await p.locator('#results article').first().getAttribute('data-opportunity');for(const l of ['en','zh','fr']){await language(l);await count(1);assert.equal(await p.getByRole('searchbox').inputValue(),'设计');assert.equal(await p.locator('#results article').first().getAttribute('data-opportunity'),before);assert(p.url().includes('tab=all'));}await visit('fr','#clubs?tab=active&geo=quebec&sport=soccer');const n=await p.locator('#results article').count();await language('en');await count(n);assert.equal(await p.locator('[data-filter=geo]').inputValue(),'quebec');assert.equal(await p.locator('[data-filter=sport]').inputValue(),'soccer');});
await check('All section labels, filters, source notes and empty states in three locales',async()=>{for(const l of ['fr','en','zh'])for(const route of ['internships','clubs','jobs','resources']){await visit(l,'#'+route);await noChinese(l);if(route==='resources')await p.locator('summary').click();await noChinese(l);if(route!=='resources'){await p.locator('[data-action=filters]').click();await noOverflow();}await p.getByRole('searchbox').fill('no-match-736x');await count(0);assert.equal(await p.locator('.empty h3').innerText(),resources[l].ui.results.emptyTitle);await noChinese(l);await p.locator('.empty [data-action=reset]').click();}});
await check('All 71 details in all three languages, with no missing translation or overflow',async()=>{await p.setViewportSize({width:320,height:740});for(const l of ['fr','en','zh']){for(const [kind,items]of [['club',source.clubs],['opportunity',source.opportunities]])for(const item of items){await visit(l,'#'+kind+'/'+item.id);await p.locator('dialog[open]').waitFor();assert.equal(await p.locator('#dialog-title').innerText(),kind==='club'?item.name:resources[l].content.opportunities[item.id].displayTitle);await noChinese(l);await noOverflow();assert(await p.locator('.detail-evidence a').count()>0);}console.log('DETAILS',l,71);}await p.setViewportSize({width:390,height:844});});
await check('Language switching inside a dialog retains the record and reading progress',async()=>{await visit('fr','#opportunity/rapid-groupsales');await p.locator('dialog[open]').waitFor();await p.locator('.dialog-body').evaluate(el=>el.scrollTop=(el.scrollHeight-el.clientHeight)*.6);for(const l of ['en','zh','fr']){await p.locator('[data-language-select]').selectOption(l);await p.waitForFunction(title=>document.querySelector('#dialog-title')?.textContent===title,resources[l].content.opportunities['rapid-groupsales'].displayTitle);assert(p.url().includes('#opportunity/rapid-groupsales'));const ratio=await p.locator('.dialog-body').evaluate(el=>el.scrollTop/(el.scrollHeight-el.clientHeight));assert(Math.abs(ratio-.6)<.03);await noOverflow();}await p.screenshot({path:out+'/fr-detail.png'});await close();assert(!(await p.locator('dialog').isVisible()));});
await check('Language selection retains list scroll position',async()=>{await visit('fr','#clubs');await p.locator('[data-club=capitales]').scrollIntoViewIfNeeded();const y=await p.evaluate(()=>scrollY);await p.evaluate(()=>document.querySelector('[data-language=en]').click());await p.waitForFunction(()=>document.documentElement.lang==='en');assert(Math.abs(await p.evaluate(()=>scrollY)-y)<2);});
await check('Read-only source data is unchanged by switches and exports',async()=>{assert.deepEqual(await p.evaluate(()=>window.HORS_JEU_DATA),source);await visit('zh');await language('fr');assert.deepEqual(await p.evaluate(()=>window.HORS_JEU_DATA),source);const download=p.waitForEvent('download');await p.locator('a[download]').click();const file=await download;await file.saveAs(out+'/source.json');assert.deepEqual(JSON.parse(await readFile(out+'/source.json','utf8')),source);});
await check('Native locale dates and plural forms',async()=>{for(const l of ['fr','en','zh']){await visit(l,'#internships?pay=unpaid');await count(2);assert.equal(await p.locator('#result-count').innerText(),resources[l].ui.results.opportunity_other.replace('{{count}}','2'));await p.getByRole('searchbox').fill('理疗');await count(1);assert.equal(await p.locator('#result-count').innerText(),resources[l].ui.results.opportunity_one.replace('{{count}}','1'));const text=await p.locator('[data-snapshot-date]').innerText();assert(l==='fr'?text.includes('sept.'):l==='en'?text.includes('Sep'):text.includes('2026'));}});
await check('Phone, tablet, landscape and desktop layouts in every language',async()=>{for(const width of [320,360,390,430,768,844,1440]){await p.setViewportSize({width,height:width===844?390:width===1440?1000:844});for(const l of ['fr','en','zh']){for(const route of ['internships','clubs','jobs','resources']){await visit(l,'#'+route);await noOverflow();}await visit(l);await p.screenshot({path:`${out}/${l}-${width}.png`});await visit(l,'#opportunity/rapid-groupsales');await p.locator('dialog[open]').waitFor();await noOverflow();}}});
await check('Blocked storage still supports French default and URL language persistence',async()=>{const isolated=await b.newContext({viewport:{width:390,height:844},locale:'en-US'});await isolated.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('Storage denied');}});});const page=await isolated.newPage();await page.goto(base);await page.locator('#results').waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'fr');await page.locator('[data-language=en]').click();await page.waitForFunction(()=>document.documentElement.lang==='en');await page.reload();await page.locator('#results').waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'en');await isolated.close();});
await check('Missing data error is localized and language control remains usable',async()=>{for(const l of ['fr','en','zh']){const page=await ctx.newPage();await page.route('**/data/catalog.js',r=>r.abort());await page.goto(base+'?lang='+l);assert.equal(await page.locator('main h2').innerText(),resources[l].ui.load.title);await page.close();}});
await check('No JavaScript errors',async()=>{assert.deepEqual(errors,[]);});
await writeFile(out+'/report.json',JSON.stringify({engine,base,checkedAt:new Date().toISOString(),checks,details:213,locales:['fr','en','zh'],errors},null,2));
console.log('ALL PASSED',checks.length);await b.close();
